package com.jw.sys.dao;

import com.jw.common.bean.BaseDao;
import com.jw.sys.bean.vo.NoticeVo;

import java.util.List;


public interface NoticeDao extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int insertSelective(NoticeVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    NoticeVo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoticeVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NoticeVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoticeVo record);


    NoticeVo selectById(Integer noticeId);

    List<NoticeVo> list(String condition);

    void insert(NoticeVo notice);

    void deleteById(Integer noticeId);

    void updateById(Integer id);

    List<NoticeVo> listAll();
}