package com.jw.sys.dao;

import com.jw.common.bean.BaseDao;
import com.jw.sys.bean.entity.Relation;

public interface RelationDao extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbggenerated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbggenerated
     */
    int insertSelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbggenerated
     */
    Relation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Relation record);

    void insert(Relation relation);

    void updateMenuRole(Relation relation);
}