package com.jw.sys.dao;

import com.jw.common.bean.BaseDao;
import com.jw.sys.bean.vo.ZTreeNode;
import com.jw.sys.bean.entity.Role;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RoleDao extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    Role selectById(Integer roleId);

    Role getSingleRoleName(Integer pid);

    Role getSingleRoleNameById(Integer roleId);

    List<Role> selectRoles(@Param("roleName") String roleName, @Param("type") Integer type , @Param("scenicId")Integer scenicId);

    void insert(Role role);

    void updateById(Role role);

    void deleteById(@Param("roleId") Integer roleId, @Param("mender") Integer mender);

    List<ZTreeNode> roleTreeList(Integer type);

    void deleteRolesById(@Param("roleId") Integer roleId, @Param("mender") Integer mender);

    List<ZTreeNode> roleTreeListByRoleId(Map<String, Object> map);

    Role selectByIdAndName(@Param("roleid") Integer roleid, @Param("roleName") String roleName, @Param("type") Integer type, @Param("scenicId")Integer scenicId);

    List<ZTreeNode> roleTreeListByUserId(Map<String, Object> map);

    List<ZTreeNode> roleTreeListByRoleIdAndUserId(Map<String, Object> map);
}