package com.jw.sys.dao;

import com.jw.common.bean.BaseDao;
import com.jw.sys.bean.entity.SysAdminLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysAdminLogDao extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbggenerated
     */
    int insert(SysAdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbggenerated
     */
    int insertSelective(SysAdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbggenerated
     */
    SysAdminLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAdminLog record);

    List<SysAdminLog> findSysAdminLogs(@Param("num") Integer num, @Param("pageSize") Integer pageSize, @Param("describe") String describe, @Param("createTime") String createTime);

    int getAdminLogCount(@Param("describe") String describe, @Param("createTime") String createTime);
}