fileurl:
  uploadurl: /mnt/softvan/gucun/tour/file/Pictures/upload/ # D:/baoshan/file/Pictures/upload/   /Users/soft/temp/upload/
  ueditorUrl: /mnt/softvan/gucun/tour/file/Pictures/ # D:/baoshan/file/Pictures/  /home/softvan/baoshan/file/Pictures/
  videoUploadUrl: /mnt/softvan/gucun/tour/file/Pictures/upload/video/
  audioUploadUrl: /mnt/softvan/gucun/tour/file/audio/
  QRCodeUrl: /mnt/softvan/gucun/tour/file/QRCode

spring:
  mvc:
    static-path-pattern: /**
    view:
      prefix: /template
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static,classpath:/public/,file:${fileurl.uploadurl},file:${fileurl.ueditorUrl}
  jackson:
    serialization:
    write-dates-as-timestamps: false
    serialization-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/gucun_test?autoReconnect=true&amp;rewriteBatchedStatements=true&characterEncoding=utf8&amp;socketTimeout=30000&amp;connectTimeout=3
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        filters: log4j,wall,mergeStat

  redis:
    host: 127.0.0.1
    pool:
      max-active: 30
      max-idle: 20
      max-wait: 15000
    password: softvan123
    port: 6379
    timeout: 25000
  servlet:
      multipart:
        max-file-size: 30Mb
        max-request-size: 30Mb

mybatis:
  type-aliases-package: com/jw/**/bean #com/jw/**/bean
  mapper-locations: classpath*:mapper/**/*Mapper.xml
mapper:
  mappers: com.jw.common.bean.BaseDao
  not-empty: false
  identity : MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

Callback:
  Key: xxx



log:
  address: /Users/soft


https:
  url: http://gucun.cs.leyoujisan.com/tour #    url: http://kargilik.xbdcar.com/baoshan  http://127.0.0.1:8091/baoshan
  domainName: http://gucun.cs.leyoujisan.com/tour
  mxp_url: http://gucun.cs.leyoujisan.com/yxpt/#/postcard?chcode=CHCODE&scanpoint=SCANPOINT&usrflag=USRFLAG    #公众号明信片跳转地址
epolicyUrl:
  url: http://



multipart:
  maxFileSize: 15Mb
  maxRequestSize: 100Mb

zfb:
  APPID: 2019073166077316
  RSA_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbZRMApQLsx1kWMp+CbDqTzK7DviWi881djPHehFh0tE32j1CSJ3ev5E2bAlwE49lHaQlUaA4XMfnwbRKSSAsahX0ZqwXHkw/BW0Qluw05uLyavNAT1euppD7ZgywwCg22rCrrueXm+rG82KagoCJmRORa8KZEzOaHpp/27W28KeooiYJwufT+mb9H6mPsCsnMY35la2b8fMrijMioKboKnBkT306BteRIR2InIkGVi5w2YYDWQ/J8ZpQAjqNeI9ObB9kwyzEEX1JMGynklEocLIVLDj4P8dbwmC0UCq098sCJrngUV+rSscQ5YmNfANxsw8ArzPknOnZn0Zv5FlTXAgMBAAECggEACdXX4g6PpNTpOpJxrhuTiY9G8HS0hR/RO76UAHV388sFtDlV7Co7VRKqJsl7cYPKWM65HHKJkcZD/4enyUJuEXupc1pzvzH7qU1RfuHb8G9U4KZatSaxB8exgqrevRulyo4TGWBmwLvVTBKaWUhJZRevLGJW47vkS2msbkCQ1XvoTHI949pBPhYcpSdDXHvAJYP6LG+yg7EIcBuVJIxGavYmb+qIlsyfpx9WzRTU/aUm8VMM6/n0Ld0/wwZ6KAOVCB5MIb19G9KFTd5UoND1sXOKrNNwWBIbTsnoz84wgTH1uVnACXeQrOhh4WAhiTuYr+cvKC/LRbj72YpiSS56oQKBgQDbtMAlfeOy1QMpuWC7vm9gLOjnEgs4+H1r9LurSiTS1Kk/ThSrpnD7dIcNDbGQc+3ChDVzlqvnDvgDqI1XdpjN82vwAOpdXE6kMaEEYVvZ+k04QzCoGjrcknoulx8UIjoavUc/coc6khZCNKzJ7ee/sercLjbJf1eNRnF/WoL1tQKBgQC1EKL0ZSB/XTkZrOhr9WBfbF625iU+WLNT/xig8FK60m01ueHPdP3oWV41OkvH791CNtzqgBhnxD2VgtJRrO20NRrI2GM+OMBhDqZtpmyeZPGPqW6rttwL1wGhERn9X7RFUQCvq3evPFhvZRwdrYKnAXV2LI5R4GciP1rwNdt32wKBgEmlPQNUP48id/z0dsh3/T1v0GIkWj6ujNwzHPU91ToWruTZd3RSRm0DkoF9pZeWRIx/ZKtqRhUdn2UaisZWqsHeZr/8jpLc7j97o02klPVsQZYqb5TptfFZ6DrVzUUic/eims9ZxJqNfYiTv5ewd456RQ+pLhQ860wf4Mufu2ZBAoGAf7AYyvMaBNewMewfCCtF6GVbMe6Ba0NQS7cFHlH8daV5wL6ygQPHH3kOl8jhskD0rwJTrsfg7iSVLX/RZCnohAJDPkpjSnjpKkkTkxYfWWBkfeSFmHDfIzZf/r85rdY1IgDq0/e+8oRC9WO/fSpkjfPYaxsmzpTLBnrZXbcNa6sCgYEAwvJkTc/AOWY58qlR89p5Sk/swRN18NEB2ux9CXj0bmJylotNc8RbwYU+NTXNAy+uvyphF9z51r7gyg4BgTDrYDgZH5jO9xUOh4uQrmVn16z7dymaJJzRu50KdYRcIncwCrquMCOG5HuFe7WPn9wUDB2YAjFfE6MzJxGKneqpfUo=
  ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhL2IAfLPNsa4i0qBIo834HqWeqZ93FlOKM5/ZolZV8+PiPasfgVnhKUc+yoFl8oaL9FZ8eQY8iyeZIVYbuUaIfU47lKDWyky80aI/nIil5zLzhD7XzkUzQV9ghfhaniUAKF7TL1LsGDjwSB3zhm0GQDPiCugyElJ5W29Ikyv6OtgQCV343eoa+N3/I95avevpn93pPqaBhkIzdDAAVO+68wYOAZsm89l7k1ur8gspZL70o1+1FxxiETGVtx7RZ+E8WJgHESn0gSSViI49ovxcYNl+s4VLKw5FUsCbW5nPQ/rdUjwyy3ISVqSJnbExjjTgwqQ7jsoABMP9M9qjDildwIDAQAB
  notify_url: http://tour.leyoujisan.com/business/api/notifyCallBack
  return_url: http://tour.vue.leyoujisan.com/#/getTicketProductList
  SIGNTYPE: RSA2
  CHARSET: utf-8
  gateway_url: https://openapi.alipay.com/gateway.do
  seller_id: 2088001619822885
  payFlag: false

METRO:
  PRIVATE_KEY: MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCUrSaXoNt7y20fnNE8WxcsmVlICQJ1JndAdKoJ+G2NOQTIKflX9ERvFF3sPhKwRWjbKKu8bxLYSEGEVs4Mj+Tkt/rWCasqODYjUHRRqmr9cvxowpoSkCwwCYcdtKLi+qTfuqUhOryekHVKBMo9cS3F858LwYDrV5xTERhfa56oUlwBKJz6aJ8fRpYtxn9dADbYoNtupSqKt1tNlPvWDI05zd9XI9vetDc1zL2CEYWPqKkUXVd2jbVyM48siM8p151EdaKCjmbu4I+SdihQ7sO6eiXUb6KnHDrl3sD8vn+JR6uaUWSSBYU0nBxY+IGEq829KxAtm2B18csUXsAfT85dAgMBAAECgf9qR1xPB63d0I0xC+iGPJdUSkqIM+iN1fFpIfxrJCsryJaif16+gN5qiSSau8SgPP23rFsXWE8gTIaJE4Q3dqUo2lt0pXS1uXj5xYlg13Gju46zVGjO3EC6FhWAJqBJoOI7DDD+j/5FWv586u+m/EC8QGpw/OIrWXVl69KAY24G48BsvRxkbXNgq5zN5q2t/M0FMN0aaFf84l8cAdtpNq8aea7Wh1wIGta6pbuO4ttLB+XcXeOT63mWNWVg9cF4XFJoElw1epIPCNnWD7esa5qFwoo4RfdkKl9+J+sjfXJXATjIayMrXYcQtsB60VqqxlvqSkq0EcYwPLqo7+HfEGUCgYEA2KWFtArgdCGsTYAT+2OQX1uyJsHCwpSVg8gYEutfescmcXQUHt0HvN3ceTRfvLn3XzZGvgY02zjQFqg0AXjysYwEYv1Z026ZicJTLI34RQUlzrkkGPnZpZxx4Zm2M32UJWCWjOa8798HRSS4eED8GXWs+jAapwoxuKPzUf1gXiMCgYEAr67igqHWufOkFw2A4OOFjVXGTL6w0bmpCH32qWF7+jkTcaU2oaSyQTh7gvd+1/jSmFuepLUpNz4HKsFimrqGFgNuxtJe2hfpbB0y/u4i31AZf7QJh1kkIw3uZUUVd6ZZNWLNI8lbMWjUDBd5n6sGZl/Dvd44tkMqgRjBZ2f0qX8CgYBgAgJdhlBvxphoA/FW/4l0aNtrR4S63EPiEaNxhvNaIrVLo+hiwQrzzNIuuGIQ7czNWe1Buthjqiq1T7c0S9gpjGZJRAMxqprKLN7VKNk0JRLbKLrxgo/MT6c8FfVjniwv4Dz3li12k7zSDHLff9T4p2iPuw+kpOTh8W4cEJBLRwKBgQCcEOThnTluaVTssa86mIPsoTUOuhvDw4W4qIW1xIbpK0jtnRHiGLfNnoqCNrC01TLn7AQLV2/sxiqBvdeFkotJBPWko/9lCPbwdyP1OcE61iJAwsPwO60Rgu+zgOJoLxtyhHmt/9MGGpS8xSHjSH/f89SkV8PTjek1U7OD0+KRqwKBgHNE2elQV8oNqPaYnYeB/Idb9VEou5qLdvNBo1OmZcrzoDS0QKlP/6frgGVSG/l4iEIkTGYHRlij3YjBaFkIwmrzxiO1AbUn759Id16EtWdWhvZvSFU6o1bLAE0+8v49ZSKO2uRvzmHkNy7gIM8g+cTnSuV//0/Hyvfh1cJsj9Sj
  APP_ID: 2019051149874243
  SIGN_TYPE: RSA
  URL: https://test-duchang-openapi.bangdao-tech.com/gateway.do

wechat:
  mp:
    appId: wx3c91eaff9e4967d2
    secret: c603642cc4ce5d2591c2fc10cbaa1335
    token: 432gfg5645gfdhsa
    aesKey:
    mchId: 1234073802
    mchKey: ZaQPLm01YGvRdN07bA3dsLex2HIqwXK9
    keyPath: /home/softvan/pjqsnsy/file/wxpay/apiclient_cert.p12
    IPAddress: 39.108.233.166